Bug 51002 반영
ALTIBASE/telegraf pull request #5
Opened 2024-07-18 02:13 UTC by jiee-altibase

Bug 51002 버그 반영으로 SQLLEN=4일때 컴파일 방법 추가함.

그 외 repository root에 LICENSE 추가함. (altibase/LICENSE 카피)

2024-07-18 02:16 UTC, Soyoon-Choi approved these changes
확인했습니다!

2024-07-18 04:05 UTC, zennken requested changes
코멘트 확인 부탁드립니다.

2024-07-18 04:05 UTC, zennken commented on README.md
> +For reference, the method for checking the SQLLEN size of unixODBC is as follows.
이 부분이 6번 항목에서 가장 먼저 와야 할 것 같습니다.

2024-07-18 04:05 UTC, zennken commented on README.md
> +CGO_LDFLAGS = "-L$HOME/unixodbc/lib -lodbc"
-lodbc도 필요한지요?

2024-07-18 04:05 UTC, zennken commented on README.md
> +CGO_CFLAGS = "-I$HOME/unixodbc/include"
앞에 export 명령 필요하지 않을까요?

2024-07-18 04:05 UTC, zennken commented on README.md
>  LD_LIBRARY_PATH = "$HOME/unixodbc/lib:$LD_LIBRARY_PATH"
export UNIX_ODBC="unixODBC installed path";
export LD_LIBRARY_PATH="${UNIX_ODBC}/lib;$LD_LIBRARY_PATH"
로 표현하면 어떨까 합니다.

2024-07-18 04:07 UTC, zennken commented
LICENSE 파일이 최상위에 있는데, 오른쪽에 license가 안 보이네요.

![image](https://github.com/user-attachments/assets/33960223-ce05-458d-a7a9-5f5a7bde9a30)

2024-07-18 05:01 UTC, jiee-altibase commented
라이센스는 main 브랜치에 있어야 보인다고 하네요. by chatGPT
main 브랜치 반영 후 확인해봐도 될까요?

2024-07-18 05:09 UTC, zennken commented
> 라이센스는 main 브랜치에 있어야 보인다고 하네요. by chatGPT main 브랜치 반영 후 확인해봐도 될까요?

License는 리뷰 완료 후 Merge 후에 확인하죠.

2024-07-18 05:10 UTC, zennken commented on README.md
> +For reference, the method for checking the SQLLEN size of unixODBC is as follows.
아니면 1번 항목 마지막에서 설명해도 될 것 같네요.

2024-07-18 07:11 UTC, jiee-altibase commented on README.md
> -CGO_CFLAGS = "-I$HOME/unixodbc/include"
위 내용은 telegraf 컴파일 시 필요한 환경변수이므로 아래 6번단계로 이동하였습니다.

2024-07-18 07:11 UTC, jiee-altibase commented on README.md
>  LD_LIBRARY_PATH = "$HOME/unixodbc/lib:$LD_LIBRARY_PATH"
적용하겠습니다.

2024-07-18 07:11 UTC, jiee-altibase commented on README.md
> +CGO_CFLAGS = "-I$HOME/unixodbc/include"
추가하겠습니다.

2024-07-18 07:11 UTC, jiee-altibase commented on README.md
> +CGO_LDFLAGS = "-L$HOME/unixodbc/lib -lodbc"
없으면 컴파일 시 에러 발생합니다.

go odbc의 api/api_unix.go 파일에 포함된 옵션입니다.
// #cgo linux LDFLAGS: -L /home/jiee/unixodbc2/lib -lodbc

2024-07-18 07:11 UTC, jiee-altibase commented on README.md
> +For reference, the method for checking the SQLLEN size of unixODBC is as follows.
항상 odbcinst -j 결과를 참고해서 빌드해야 한다. 라는 말씀이시죠?

2024-07-18 23:25 UTC, zennken commented
문서 작성 시 최소 3명의 관점에서 봐야 할 것 같습니다.

1. 개발자 관점: 프로그램 작성자 관점에서 필요한 말을 다 했는지.
2. 기술자 관점: 어느 정도 해당 제품에 대해 아는 사용자 시점에서 필요한 고급 정보 (예를 들어  프로퍼티 설정 등)를 제공했는지.
3. 초보 관점: 해당 제품을 처음 접하는 사용자 시점에서 따라 할 수 있는지.

완벽하게 할 수는 없겠지만, 적어도 3가지 시점에서 보고 투입되는 리소스와 결과물의 품질간 trade-off를 정하면 좋을 것 같습니다.

2024-07-19 02:01 UTC, jiee-altibase commented
6단계 수정해서 커밋했는데 확인 부탁드립니다.

2024-07-19 02:22 UTC, jiee-altibase commented
리뷰 내용 전체 반영해서 커밋했습니다.
확인 부탁드립니다.

2024-07-22 22:13 UTC, zennken commented
수고하셨습니다.  6. Compile Telegraf embedded the Altibase input plugin 내용 확인했습니다.

"1. Intall and configure unixODBC
에서 코멘트 남긴 아래 내용 적용여부 확인 부탁드립니다.

_[Altibase와 unixODBC 연동 가이드](https://docs.altibase.com/pages/viewpage.action?pageId=11698379) 링크연결해주고, 한글이지만 구글 번역기로 보면 된다라고 가이드해 주면 어떨까 싶네요.

알티베이스를 모르는 사람 입장에서 생각해보니까 여기서부터 막히지 않을까 싶네요._

2024-07-22 22:33 UTC, Soyoon-Choi commented on README.md
링크에 관련하여... [ODBC User's Manual](https://github.com/ALTIBASE/Documents/blob/master/Manuals/Altibase_trunk/eng/ODBC%20User's%20Manual.md#2-installing-and-configuring-the-altibase-odbc-driver) 여기의 내용과는 많이 다른 건가요? 설명을 추가하는 건 좋아보입니다.

2024-07-23 05:42 UTC, jiee-altibase commented on README.md
odbc manual과 unixodbc 가이드는 내용이 달라서 위 팀장님이 주신 문서로 링크 추가하겠습니다.

2024-07-23 06:24 UTC, zennken approved these changes
수고하셨습니다.

2024-07-23 06:24 UTC, zennken commented on README.md
> +For reference, the method for checking the SQLLEN size of unixODBC is as follows.
> 항상 odbcinst -j 결과를 참고해서 빌드해야 한다. 라는 말씀이시죠?

네~맞습니다. 위 명령의 결과에 따라 Compile 수행시 액션이 달라지기 때문에, 인과 관계로 설명하는 것이 좋을 것 같습니다.

2024-07-23 06:24 UTC, zennken commented on README.md
> -CGO_CFLAGS = "-I$HOME/unixodbc/include"
네~잘하셨습니다. 안 그래도 여기 있는 게 좀 어색하다고 생각하고 있었습니다. :)

2024-07-23 06:24 UTC, zennken commented on README.md
> +cd telegraf
환경변수 셋업하는 부분과 실제 컴파일 하는 부분은 분리하는 게 좋을 것 같습니다. 이유는 32/64에 따라 환경 변수는 달라지지만, 컴파일 명령은 동일하기 때문에 내용이 중복되기 때문입니다.

2024-07-23 06:24 UTC, zennken commented on README.md
> +CGO_LDFLAGS = "-L$HOME/unixodbc/lib"
여기는 -lodbc 옵션이 필요없는지요?

2024-07-23 06:24 UTC, zennken commented on README.md
> -CGO_CFLAGS = "-I$HOME/unixodbc/include"
차라리 여기다 [Altibase와 unixODBC 연동 가이드](https://docs.altibase.com/pages/viewpage.action?pageId=11698379) 링크연결해주고, 한글이지만 구글 번역기로 보면 된다라고 가이드해 주면 어떨까 싶네요. 

알티베이스를 모르는 사람 입장에서 생각해보니까 여기서부터 막히지 않을까 싶네요.

2024-07-23 06:24 UTC, zennken commented on README.md
ODBC 사용자 매뉴얼의 내용은 윈도우에서 연동을 설명하지만, 여기서는 unixODBC 연동 방법에 대한 가이드가 필요할 것 같습니다.

2024-07-23 06:24 UTC, zennken commented on README.md
> +For more information about unixODBC settings, please refer to [unixODBC Guide for Altibase(Korean)](https://docs.altibase.com/pages/viewpage.action?pageId=11698379).
알티베이스에 연결하기 위해 작업이 필요하다고 명시적으로 써 줘야 할 것 같습니다.

2024-07-24 01:26 UTC, jiee-altibase commented
fix BUG-51002

2024-07-24 01:34 UTC, merged

2024-07-24 01:37 UTC, Soyoon-Choi commented on README.md
> +To establish a connection between the installed unixODBC and Altibase server, further configuration is necessary. As this process falls beyond the scope of this guide, please refer to [unixODBC Guide
```suggestion
To establish a connection between the installed unixODBC and the Altibase server, further configuration is necessary. As this process falls beyond the scope of this guide, please refer to the [unixODBC Guide for Altibase (Korean)](https://docs.altibase.com/x/y4Cy) for detailed instructions.
```

2024-07-24 01:37 UTC, Soyoon-Choi commented on README.md
> +Before compiling Telegraf embedded the Altibase input, you need to set some environment variables.
```suggestion
Before compiling Telegraf with the embedded Altibase input, you need to set some environment variables.
```

2024-07-24 01:37 UTC, Soyoon-Choi commented on README.md
> +This depends on the SQLLEN size of unixODBC, so check the SQLLEN size by executing the command below.
```suggestion
The required settings depend on the SQLLEN size of unixODBC. Check the SQLLEN size by executing the command below:
```

2024-07-24 01:38 UTC, Soyoon-Choi commented on README.md
> +Then, set environment variables according to SQLLEN size.
```suggestion
Then, set the environment variables according to the SQLLEN size.
```

2024-07-24 01:38 UTC, Soyoon-Choi commented on README.md
> +If SQLLEN=8
```suggestion
If SQLLEN=8:
```

2024-07-24 01:38 UTC, Soyoon-Choi commented on README.md
> +If SQLLEN=4
```suggestion
If SQLLEN=4:
```

2024-07-24 01:38 UTC, Soyoon-Choi commented on README.md
> +Finally, navigate to the Telegraf directory and execute the following command to compile Telegraf embedded the Altibase input plugin:
```suggestion
Finally, navigate to the Telegraf directory and execute the following command to compile Telegraf with the embedded Altibase input plugin:
```

2024-07-24 01:39 UTC, Soyoon-Choi commented
죄송합니다 코멘트를 커밋한 줄 알았어요ㅠㅠ 내용적으로 바뀐 부분은 없고 간단한 문법 수정이니 혹시 반영 가능할까요?